"""Assembly guard for the PR-Review rescope: feature `08`, the integration point.

Features `01`-`07` each shipped an agent, a skill, or a propagator capability that
passed review in isolation. This module is the standing proof that they compose:
that the roster is exactly seven, that no renumbered predecessor survives anywhere,
that the three documentation surfaces describe the family that actually exists, and
that propagation reaches a fixed point.

Three pattern classes, not one
------------------------------
A sweep built from the agent registry matches slugs and `name:` display names. Both
miss the form that actually survived in the two documentation surfaces: the
unhyphenated prose form, which is neither a slug nor a `name:` value. That is
precisely how it outlived a rename the propagator otherwise rewrites automatically
(`_rewrite_agent_references` keys on the display name).

Renumbering makes display names sharper than slugs here. `05g Artifact Sweeper`
became `05c Artifact Sweeper` while `05g` was reissued to the Readiness
Synthesizer -- so a bare `05g` sweep matches a live agent and proves nothing. The
old names are therefore listed whole, never by prefix.
"""

import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
GITHUB_AGENTS_DIR = REPO_ROOT / "source_of_truth" / "agents"

# ---------------------------------------------------------------------------
# The settled roster
# ---------------------------------------------------------------------------

# The seven survivors, contiguous `05a`-`05g`, plus the orchestrator that
# dispatches them. Security is delegated to `04e-diff-security-scan`, which is a
# different family and is not a member of this roster.
PR_REVIEW_ORCHESTRATOR_SLUG = "05-pr-review"
PR_REVIEW_ROSTER = (
    "05a-baseline-worktree",
    "05b-change-narrator",
    "05c-artifact-sweeper",
    "05d-consistency-auditor",
    "05e-dependency-auditor",
    "05f-test-health",
    "05g-readiness-synthesizer",
    "05h-cleanliness-auditor",
)
DELEGATED_SECURITY_SCAN_SLUG = "04e-diff-security-scan"

# Renumbered predecessors. Listed whole -- see the module docstring on why a
# prefix sweep would match live agents.
#
# `05c`-`05f` and `05i` (the five deleted evaluators) are NOT repeated here:
# `tests/test_retired_evaluator_removal.py` owns those names and is their single
# definition. Re-listing them would fork the list.
RENUMBERED_PREDECESSORS = (
    ("05g-artifact-sweeper", "05g Artifact Sweeper"),
    ("05h-test-health", "05h Test Health"),
    ("05j-consistency-auditor", "05j Consistency Auditor"),
    ("05k-dependency-auditor", "05k Dependency Auditor"),
    ("05l-readiness-synthesizer", "05l Readiness Synthesizer"),
)
OLD_SLUGS = tuple(slug for slug, _ in RENUMBERED_PREDECESSORS)
OLD_DISPLAY_NAMES = tuple(name for _, name in RENUMBERED_PREDECESSORS)

# The retired orchestrator, in all three of its forms.
RETIRED_ORCHESTRATOR_SLUG = "05-phase-final-review"
RETIRED_ORCHESTRATOR_DISPLAY_NAME = "05 Phase - Final Review"

# Skills and the Claude command, renamed by feature `03` / regenerated by `04`.
RETIRED_SKILL_DIRS = ("phase-final-review-conventions", "phase-final-review-report")
RETIRED_COMMAND = "ports/claude/commands/phase-final-review.md"

# ---------------------------------------------------------------------------
# The three documentation surfaces AC6 names
# ---------------------------------------------------------------------------

DOC_SURFACES = (
    "USAGE.md",
    "docs/CODEBASE_CONTEXT.md",
    "README.md",
)

# The roots that actually ship: authored source assets and their generated
# copies. This is an ALLOWLIST, not an exclusion list, and that direction is
# deliberate. A retired skill or command name is only harmful where something
# loads it -- an agent body pointing at a skill directory that no longer exists
# is a load failure. Those live here and nowhere else.
#
# An exclusion list answers "what may keep the name?", and every false positive
# it produces is closed by appending one more exemption until the sweep no
# longer sweeps. An allowlist answers "where would it hurt?", which does not
# grow under pressure.
#
# `tests/` is outside it for a reason worth stating: a test that asserts a name
# is gone has to write the name down. `test_pr_review_skills.py` holds the
# rename map itself, and `test_readiness_synthesis_agents.py` asserts the old
# skill names are absent from the synthesizer's prose. Sweeping those would fire
# on the guards for the very thing being swept, and the only way to keep it
# green would be to exempt them -- which is how a sweep dies.
SHIPPED_ASSET_PREFIXES = (
    "source_of_truth/agents/",
    "source_of_truth/skills/",
    "source_of_truth/instructions/",
    "ports/claude/",
    "ports/opencode/",
    "ports/codex/",
    "ports/cursor/",
    "ports/github/",
    ".github/",
)

# The propagated copy of an exempt source. Generated, not authored: fixing it
# means editing `source_of_truth/learnings/`, which is an exempt historical record, so
# sweeping it would demand a change the exemption forbids.
GENERATED_EXEMPT_PREFIXES = (
    "ports/claude/learnings/",
    "ports/github/learnings/",
    ".github/learnings/",
    "ports/cursor/rules/",
)


def _is_shipped_asset(path: str) -> bool:
    return path.startswith(SHIPPED_ASSET_PREFIXES) and not path.startswith(
        GENERATED_EXEMPT_PREFIXES
    )


def _tracked_files() -> list[str]:
    listing = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return [path for path in listing.split("\0") if path]


def _read(path: str) -> str:
    return (REPO_ROOT / path).read_text(encoding="utf-8")


def _source_agent_slugs() -> set[str]:
    """Every agent definition on disk, read from the source of truth.

    Two files intentionally lack the `.agent.md` suffix (`prod-code-review.md`
    and `docs-writer.md`) and are still agent definitions, so this globs `*.md`
    and drops the catalogue instead of trusting the suffix.
    """
    return {
        path.name.split(".")[0]
        for path in GITHUB_AGENTS_DIR.glob("*.md")
        if path.name != "README.md"
    }


# ---------------------------------------------------------------------------
# AC5 -- the roster is exactly seven plus the delegated security scan
# ---------------------------------------------------------------------------


def test_pr_review_roster_is_exactly_eight_contiguous_agents() -> None:
    """AC5. `05a`-`05g` exist, contiguous, with nothing above `05g`.

    Derived from disk rather than restated: the roster is whatever `.github/
    agents/` holds, and this asserts that set equals the settled eight. An
    eighth evaluator appearing, or one of the seven vanishing, both fail.
    """
    on_disk = {
        slug
        for slug in _source_agent_slugs()
        if slug.startswith("05") and slug != PR_REVIEW_ORCHESTRATOR_SLUG
    }
    assert on_disk == set(PR_REVIEW_ROSTER), (
        "the PR Review roster drifted from the settled eight: "
        f"unexpected={sorted(on_disk - set(PR_REVIEW_ROSTER))}, "
        f"missing={sorted(set(PR_REVIEW_ROSTER) - on_disk)}"
    )


def test_orchestrator_and_delegated_security_scan_both_exist() -> None:
    """AC5. The roster is seven *plus* the delegated scan -- not seven alone.

    `04e` is the whole reason retiring the phase-shaped security-rollup
    evaluator was a shape change rather than a coverage regression. If `04e`
    disappears, that justification silently stops holding.

    That evaluator is deliberately not named here. Its slug lives exactly once,
    in `tests/test_retired_evaluator_removal.py`'s `RETIRED_AGENTS`, and that
    module sweeps every tracked non-exempt file for it -- so spelling it out in
    this docstring both forks the list and trips the sweep. It did: this module
    named it, and `test_no_tracked_file_references_a_retired_agent` failed as
    soon as the file was committed and `git ls-files` began to see it. The sweep
    was right and the docstring was wrong; the exemption that would have
    silenced it is the thing the sweep exists to refuse.
    """
    for slug in (PR_REVIEW_ORCHESTRATOR_SLUG, DELEGATED_SECURITY_SCAN_SLUG):
        assert (GITHUB_AGENTS_DIR / f"{slug}.agent.md").exists(), (
            f"{slug} is missing from source"
        )


def test_no_renumbered_predecessor_slug_survives_anywhere() -> None:
    """AC5. No `05h`-`05l` slug survives in source or any generated root.

    Renumbering leaves two kinds of debris: a stale source file, and a
    slug-keyed generated output that the pruner missed. OpenCode keys filenames
    on the source slug, so it is the root where a renumber orphan actually
    lands; Claude and Codex key on the stem and survive a renumber with
    filenames intact. All three are checked rather than the one that failed
    before.
    """
    roots = (
        GITHUB_AGENTS_DIR,
        REPO_ROOT / "ports" / "claude" / "agents",
        REPO_ROOT / "ports" / "opencode" / "agents",
        REPO_ROOT / "ports" / "codex" / "agents",
        REPO_ROOT / "ports" / "codex" / "profiles",
    )
    offenders = [
        str(path.relative_to(REPO_ROOT))
        for root in roots
        if root.exists()
        for path in root.iterdir()
        if any(path.name.startswith(slug) for slug in OLD_SLUGS)
    ]
    assert not offenders, "renumbered-predecessor outputs survived: " + ", ".join(
        offenders
    )


def test_roster_propagates_to_all_three_generated_roots() -> None:
    """AC5. Every survivor reaches Claude, OpenCode, and Codex.

    The three roots key filenames differently, which is exactly why a rename is
    able to reach two of them and silently miss the third.
    """
    missing: list[str] = []
    for slug in PR_REVIEW_ROSTER:
        stem = slug.split("-", 1)[1]
        for candidate in (
            REPO_ROOT / "ports" / "claude" / "agents" / f"z-{stem}.md",
            REPO_ROOT / "ports" / "opencode" / "agents" / f"{slug}.md",
            REPO_ROOT / "ports" / "codex" / "agents" / f"z-{stem}.toml",
        ):
            if not candidate.exists():
                missing.append(str(candidate.relative_to(REPO_ROOT)))
    assert not missing, "roster stopped propagating to: " + ", ".join(missing)


# ---------------------------------------------------------------------------
# AC6 -- no dangling references on the documentation surfaces
# ---------------------------------------------------------------------------


def test_documentation_surfaces_carry_no_old_slug_or_display_name() -> None:
    """AC6. No renumbered predecessor, in slug or display-name form."""
    offenders: list[str] = []
    for surface in DOC_SURFACES:
        text = _read(surface)
        found = sorted(
            {
                name
                for name in OLD_SLUGS
                + OLD_DISPLAY_NAMES
                + (RETIRED_ORCHESTRATOR_SLUG, RETIRED_ORCHESTRATOR_DISPLAY_NAME)
                if name in text
            }
        )
        if found:
            offenders.append(f"{surface}: {', '.join(found)}")
    assert not offenders, "retired identifiers survive:\n" + "\n".join(offenders)


def test_no_shipped_asset_names_a_retired_skill_or_command() -> None:
    """AC6. The `phase-final-review-*` skill and command names are gone.

    Feature `03` renamed both skill directories and feature `04` regenerated the
    command. A surviving reference points a live agent at a skill that no longer
    exists -- a load failure, not a cosmetic one.

    Swept across every shipped asset root; see `SHIPPED_ASSET_PREFIXES` for why
    that set is an allowlist.
    """
    needles = RETIRED_SKILL_DIRS + (RETIRED_COMMAND,)
    offenders: list[str] = []
    for path in _tracked_files():
        if not _is_shipped_asset(path):
            continue
        try:
            text = _read(path)
        except (UnicodeDecodeError, FileNotFoundError, IsADirectoryError):
            continue
        found = sorted({name for name in needles if name in text})
        if found:
            offenders.append(f"{path}: {', '.join(found)}")
    assert not offenders, "retired skill/command names survive:\n" + "\n".join(
        offenders
    )


def test_retired_skill_directories_are_absent_from_every_root() -> None:
    """AC6. The backstop for the sweep above.

    The sweep reads file *contents*; this asserts the directories themselves are
    gone from source and all three generated roots. Without it, a sweep scoped
    to shipped assets could pass while the retired skill still sits on disk
    waiting to be loaded by name.
    """
    roots = (
        REPO_ROOT / "source_of_truth" / "skills",
        REPO_ROOT / "ports" / "claude" / "skills",
        REPO_ROOT / "ports" / "opencode" / "skills",
        REPO_ROOT / "ports" / "codex" / "skills",
    )
    offenders = [
        str((root / name).relative_to(REPO_ROOT))
        for root in roots
        for name in RETIRED_SKILL_DIRS
        if (root / name).exists()
    ]
    assert not offenders, "retired skill directories survive: " + ", ".join(offenders)


# ---------------------------------------------------------------------------
# AC6c -- .gitignore reconciliation
# ---------------------------------------------------------------------------


def test_gitignore_carries_no_retired_fixture_rule() -> None:
    """AC6c. The `dev/phase-final-review/` rules are gone.

    They un-ignored a fixture tree that this feature retires, so they now guard
    nothing at all.
    """
    assert "dev/phase-final-review/" not in _read(".gitignore"), (
        "the retired fixture's .gitignore rules survive"
    )


def test_gitignore_tracks_the_pr_review_fixture_and_ignores_run_output() -> None:
    """AC6c. The functional half of DD-1: both directions, via real traversal.

    Asserted against what git *does*, not against the rule text, and not with
    `git check-ignore` -- which was the obvious primitive and is wrong twice
    over. It exits 0 when any rule matches *including a negation*, so an
    explicitly un-ignored path is indistinguishable from an ignored one; and its
    per-path pattern matching disagrees with real directory traversal for nested
    paths, so it reports "no rule matched" for a file whose parent directory is
    excluded. A guard built on it passed while both halves of this contract were
    broken, until the mutation sweep exposed it.

    So: the fixture is asserted *tracked* (ground truth -- git already committed
    it), and the run root is asserted invisible to `git status`, which is
    traversal, which is the thing that decides whether dry-run output pollutes a
    commit. The temporary file is the only way to observe traversal; it lands in
    the ignored area under test and is removed unconditionally.
    """
    fixture = "tests/fixtures/pr-review/pinned-diff-range.md"
    tracked = subprocess.run(
        ["git", "ls-files", "--error-unmatch", fixture],
        cwd=REPO_ROOT,
        capture_output=True,
    )
    assert tracked.returncode == 0, (
        f"{fixture} is not tracked -- the pinned fixture cannot be committed, so "
        "the dry run has no reproducible input"
    )

    # The check above reads the index, which `.gitignore` cannot affect: an
    # already-tracked file stays tracked whatever the rules say. It proves the
    # fixture is committed; it proves nothing about whether the rules let
    # the *next* fixture file be added. Only a new path exercises that, so both
    # directions are observed the same way -- through traversal.
    assert _git_sees(
        "tests/fixtures/pr-review/mutation-probe.md", cleanup=None
    ), (
        "a new file under tests/fixtures/pr-review/ is ignored -- the fixture "
        "directory has become untrackable, so the fixture cannot be maintained"
    )
    assert not _git_sees(
        "dev/pr-review/abc1234-20260716T000000Z/readiness-report.md",
        cleanup="dev/pr-review/abc1234-20260716T000000Z",
    ), (
        "dry-run output is visible to git status -- a run would offer its own "
        "reports for commit as repository noise"
    )


def _git_sees(rel_path: str, cleanup: str | None) -> bool:
    """Whether git shows `rel_path` as untracked -- i.e. does not ignore it.

    Creates the file, asks `git status`, removes it (`cleanup` names a directory
    to remove wholesale when the file's parent had to be created). Real traversal
    is the only honest oracle: `git check-ignore` matches patterns per-path and
    reports "no rule matched" for a file whose *parent directory* is excluded, so
    it disagrees with what git actually does for exactly the nested paths this
    contract is about.
    """
    import shutil

    path = REPO_ROOT / rel_path
    assert not path.exists(), f"scratch path {rel_path} already exists"
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("scratch", encoding="utf-8")
        status = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=all"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    finally:
        path.unlink(missing_ok=True)
        if cleanup:
            shutil.rmtree(REPO_ROOT / cleanup, ignore_errors=True)

    return rel_path in status


# ---------------------------------------------------------------------------
# AC7 -- the stale command
# ---------------------------------------------------------------------------


def test_stale_claude_command_is_absent() -> None:
    """AC7. The sharpest dangling reference in the repo.

    A surviving command file stays user-invocable and points at a deleted agent:
    unlike a stale prose mention, a user can run it.
    """
    assert not (REPO_ROOT / RETIRED_COMMAND).exists(), (
        f"{RETIRED_COMMAND} is still invokable and points at a deleted agent"
    )


def test_replacement_claude_command_exists_and_is_derived_not_assumed() -> None:
    """AC7. The replacement exists, and its name comes from the propagator.

    The filename is derived by `_claude_identifier_for` from the orchestrator's
    own `name:`, so this asks the propagator what it generates rather than
    hard-coding `pr-review.md` and hoping.
    """
    import sys

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import propagate_master_assets as mod

    agents = {agent.source_slug: agent for agent in mod.load_source_agents()}
    orchestrator = agents[PR_REVIEW_ORCHESTRATOR_SLUG]
    stems = mod._discover_existing_stems(mod.CLAUDE_AGENTS_DIR)
    identifier = mod._claude_identifier_for(orchestrator, stems)

    command = REPO_ROOT / "ports" / "claude" / "commands" / f"{identifier}.md"
    assert command.exists(), (
        f"the propagator derives {identifier!r} for the orchestrator, but "
        f"{command.relative_to(REPO_ROOT)} does not exist"
    )


# ---------------------------------------------------------------------------
# AC8 -- propagation reaches a fixed point
# ---------------------------------------------------------------------------


def _changes(counters: dict) -> dict:
    import sys

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import propagate_master_assets as mod

    return mod.propagation_changes(counters)


def test_propagation_is_idempotent() -> None:
    """AC8. Two consecutive runs; the second reports zero changes.

    Run against an isolated consumer, so the first run does the real work from
    an empty tree and the second has nothing left to do. That ordering is the
    point: asserting only that a settled tree does not move would pass on a
    propagator that never converges from scratch.
    """
    import shutil
    import tempfile

    import _propagate_env as env

    with tempfile.TemporaryDirectory() as tmp:
        consumer = Path(tmp) / "consumer"
        consumer.mkdir()
        shutil.copytree(REPO_ROOT / "source_of_truth", consumer / "source_of_truth")

        # `propagate_once` reads its source from the redirected `source_of_truth`, so
        # copying the source tree into the consumer is all the isolation this needs.
        with env.redirect(consumer):
            env.mod.propagate_once(verbose=False)
            second = env.mod.propagate_once(verbose=False)

    assert not _changes(second), (
        "a second consecutive propagation run still changed things: "
        f"{_changes(second)}. Propagation must be a fixed-point operation."
    )


def test_committed_tree_is_at_a_propagation_fixed_point() -> None:
    """AC8. The committed generated roots match what the source produces.

    Distinct from idempotency above, and the stronger claim: propagation is
    *not* idempotent across an agent-identifier reclassification. Identifier
    resolution reads on-disk stems, so removing a subagent file changes the
    identifier computed on the next run -- this tree has needed three runs to
    converge. A single run therefore leaves a valid-looking but non-converged
    tree, which is why "I ran the propagator" is not evidence and this asserts
    the settled state instead.

    This writes to the working tree only when it is already wrong, in which case
    the write is the repair and the failure is the report.
    """
    import _propagate_env as env

    counters = env.mod.propagate_once(verbose=False)
    assert not _changes(counters), (
        "the committed tree is not at a propagation fixed point; a run still "
        f"changed things: {_changes(counters)}. Run propagation repeatedly until "
        "every change counter is zero, then commit the result."
    )


# ---------------------------------------------------------------------------
# Retirement of the phase-shaped fixture
# ---------------------------------------------------------------------------


def test_retired_phase_shaped_fixture_is_gone() -> None:
    """The Phase document's retirement instruction, finally executed.

    It was dismissed as "moot -- the directory does not exist", which was true
    of the report root and false of the fixture tree, so no feature inherited
    it. It was then left alone by four successive features on the recorded
    grounds that seven surviving agents named it as live wiring.

    That claim conflated two roots. The seven agents named the *report* root
    (`dev/phase-final-review/PHASE_0N/`), never the *fixture* root; feature `07`
    completed that migration to `dev/pr-review/`. No agent has ever named the
    fixture tree. Its actual consumers were the five phase-shaped evaluators,
    which feature `02` deleted -- and its `PHASE_05a`/`PHASE_05b` pseudo-subphase
    shape is the phase premise this whole rescope retired. Its replacement is
    `tests/fixtures/pr-review/pinned-diff-range.md`.
    """
    assert not (REPO_ROOT / "dev" / "phase-final-review").exists(), (
        "the phase-shaped fixture tree survives"
    )


def test_claude_agents_root_holds_only_the_catalogue_and_generated_output() -> None:
    """The pre-existing orphan the marker-guarded pruner can never remove.

    `claude/agents/single-feature.md` predates the generated marker, so
    `_is_generated_output` cannot recognise it and the pruner fails closed --
    correctly, because that same guard is what stops it deleting the
    hand-maintained `claude/agents/README.md`. The two are indistinguishable to
    the pruner, which is why this needed a human decision rather than a pruner
    change.

    They are not indistinguishable to a reader. `README.md` is documentation.
    `single-feature.md` is a loadable Claude subagent definition with no source:
    it declares `name: single-feature` and `tools: Skill`, while the real source
    (`single-feature-agent.agent.md`) declares `Single Feature - Agent` and a
    six-tool grant. It is a stale, divergent second copy of a live agent that
    Claude Code would load -- the reason it is deleted rather than exempted.

    Asserted as a derived invariant, not a name list: every file here is either
    the catalogue or carries the marker. A future orphan fails this without
    anyone remembering to add it.
    """
    import sys

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import propagate_master_assets as mod

    unexplained = [
        path.name
        for path in sorted((REPO_ROOT / "ports" / "claude" / "agents").glob("*.md"))
        if path.name != "README.md"
        and not mod._is_generated_output(path, mod.GENERATED_AGENT_MARKDOWN_HEADER)
    ]
    assert not unexplained, (
        "unmarked, unsourced files in claude/agents/: "
        + ", ".join(unexplained)
        + " -- these load as agents but no source produces them"
    )


def test_superseded_execution_manifest_is_deleted() -> None:
    """The pre-rescope manifest describes a decomposition that never shipped.

    `dev/feature/phase-03-pr-review-execution-manifest.md` supersedes it. Two
    manifests for one phase is an invitation to read the wrong one.
    """
    superseded = REPO_ROOT / "dev" / "feature" / (
        "phase-03-phase-final-review-execution-manifest.md"
    )
    assert not superseded.exists(), f"{superseded.name} supersedes nothing and survives"
